version: "3.7"
services:
#   jenkins:
#     container_name: jenkins
#     image: jenkinsci/blueocean
#     user: root
#     ports:
#       - "8080:8080"
#       - "8443:8443"
#       - "50000:50000"
#     volumes:
#       - ./jenkins_data:/var/jenkins_home
#       ##### Mac OS X and Linux ONLY #####
#       - /var/run/docker.sock:/var/run/docker.sock

  flask_app:
    container_name: flask_app
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 5000:5000

